name: Java CI with Allure, Unit & Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      ### 1. Set up environment
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      ### 2. Run Unit Tests with Coverage and Allure
      - name: Run Unit Tests
        run: |
          mvn clean test -Punit-tests
          mvn jacoco:report
          mvn allure:report

      ### 3. Run Integration Tests with Allure
      - name: Run Integration Tests
        run: |
          mvn verify -Pintegration-tests
          mvn allure:report

      ### 4. Upload Allure and Code Coverage Reports
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: target/site/jacoco
