name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI Workflow
    runs-on: ubuntu-latest

    steps:
    # 1. Setup Environment
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js (or change to Java/Python/etc.)
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      #run: npm ci
      run: echo "npm ci"

    # 2. Run Unit Tests and Code Coverage
    - name: Run Unit Tests with Coverage
      #run: npm run test:unit -- --coverage
      run: echo "npm run test:unit -- --coverage"
      env:
        CI: true

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/

    # Optional: Push coverage to Codecov (or Coveralls)
    - name: Upload coverage to Codecov
      # uses: codecov/codecov-action@v4
      # with:
      #   token: ${{ secrets.CODECOV_TOKEN }}
      run: echo "Upload coverage to Codecov"

    # 3. Run Integration Tests
    - name: Run Integration Tests
      #run: npm run test:integration
      run: echo "npm run test:integration"
      env:
        CI: true
